#pragma once
#include <SFML/Graphics.hpp>
#include <SFML/OpenGL.hpp>
#include <SFML/Audio.hpp>
#include <cmath>
#include <GL/glut.h>
#include <ctime>
#include <sstream>
#include <iostream>
#include <locale>
#include <string.h>
#include <windows.h>
#include <string>
